version: "3.9"
services:
  #TODO: add pgbouncer or pgcat and several instances of postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - database-volume:/var/lib/postgresql/data
  
  pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER="${DATABASE_USER}"
       - DB_PASSWORD="${DATABASE_PASSWORD}"
       - DB_HOST=postgres
       - DB_NAME="${DATABASE_NAME}" 
       - POOL_MODE=transaction
    ports:
      - "5432:5432"
    depends_on:
      - postgres
    
  api:
    build: .
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "3007-3008:3005"
      - "50053-50054:50051"
    depends_on:
      - liquibase
  
  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./configs/migrations:/liquibase/changelog
    command: [
        "liquibase",
        "--username=${DATABASE_USER}",
        "--password=${DATABASE_PASSWORD}",
        "--changeLogFile=changelog/db.changelog-root.xml",
        "--url=${DATABASE_URL}",
        "update"
    ]
    depends_on:
      - pgbouncer
  
  nginx:
    image: nginx
    volumes:
      - ./configs/templates/nginx:/etc/nginx/templates
    ports:
      - "10002:80"
    environment:
      - HOST_API=${HOST_API}
    depends_on:
      - api

  nginxGRPC:
    image: nginx
    volumes:
      - ./configs/templates/nginxGRPC:/etc/nginx/templates
      - ./configs/tls:/etc/nginx/certs
    ports:
      - "10003:1443"
    environment:
      - HOST_API=${HOST_API}
    depends_on:
      - api

volumes:
  database-volume:
networks:
  default:
    name: indefinite-studies-profiles-service-network