version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_MULTIPLE_DATABASES: "${DATABASE_NAME_PREFIX}_1,${DATABASE_NAME_PREFIX}_2,${DATABASE_NAME_PREFIX}_3,${DATABASE_NAME_PREFIX}_4"
    volumes:
      - ./scripts/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - database-volume:/var/lib/postgresql/data

  api:
    build: .
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "3007-3008:3005"
      - "50053-50054:50051"
    depends_on:
      - liquibase_shard_1
      - liquibase_shard_2
      - liquibase_shard_3
      - liquibase_shard_4
      - postgres

  liquibase_shard_1:
    image: liquibase/liquibase
    volumes:
      - ./docker/liquibase/migrations:/liquibase/changelog
    command:
      [
        "liquibase",
        "--username=${DATABASE_USER}",
        "--password=${DATABASE_PASSWORD}",
        "--changeLogFile=changelog/db.changelog-root.xml",
        "--url=${DATABASE_URL}_1",
        "update"
      ]
    depends_on:
      - postgres

  liquibase_shard_2:
    image: liquibase/liquibase
    volumes:
      - ./docker/liquibase/migrations:/liquibase/changelog
    command:
      [
        "liquibase",
        "--username=${DATABASE_USER}",
        "--password=${DATABASE_PASSWORD}",
        "--changeLogFile=changelog/db.changelog-root.xml",
        "--url=${DATABASE_URL}_2",
        "update"
      ]
    depends_on:
      - postgres

  liquibase_shard_3:
    image: liquibase/liquibase
    volumes:
      - ./docker/liquibase/migrations:/liquibase/changelog
    command:
      [
        "liquibase",
        "--username=${DATABASE_USER}",
        "--password=${DATABASE_PASSWORD}",
        "--changeLogFile=changelog/db.changelog-root.xml",
        "--url=${DATABASE_URL}_3",
        "update"
      ]
    depends_on:
      - postgres

  liquibase_shard_4:
    image: liquibase/liquibase
    volumes:
      - ./docker/liquibase/migrations:/liquibase/changelog
    command:
      [
        "liquibase",
        "--username=${DATABASE_USER}",
        "--password=${DATABASE_PASSWORD}",
        "--changeLogFile=changelog/db.changelog-root.xml",
        "--url=${DATABASE_URL}_4",
        "update"
      ]
    depends_on:
      - postgres

  nginx:
    image: nginx
    volumes:
      - ./configs/templates/nginx:/etc/nginx/templates
    ports:
      - "10002:80"
    environment:
      - HOST_API=${HOST_API}
    depends_on:
      - api

  nginxGRPC:
    image: nginx
    volumes:
      - ./configs/templates/nginxGRPC:/etc/nginx/templates
      - ./configs/tls:/etc/nginx/certs
    ports:
      - "10003:1443"
    environment:
      - HOST_API=${HOST_API}
    depends_on:
      - api

volumes:
  database-volume:
networks:
  default:
    name: indefinite-studies-profiles-service-network
